stages:
  data_loading:
    cmd: python src/load_data.py --path=params.yaml
    deps:
    - src/load_data.py
    - gender-classification-dataset.zip
    params:
    - paths


  preprocessing:
    cmd: python src/preprocessing.py --path=params.yaml
    deps:
    - src/preprocessing.py
    params:
    - base
    - paths
    - preprocessing


  training:
    cmd: python src/model.py --path=params.yaml
    deps:
    - src/model.py
    params:
    - paths
    - base
    - training
    - preprocessing
    outs:
    - model/GR.h5